name: Aggiorna Menu Settimanale

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Installa librerie
        run: pip install -U google-generativeai

      - name: Esegui Script Python
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python spesa/automazione.py

      - name: Salva su GitHub
        run: |
          git config --global user.name 'Robot Menu'
          git config --global user.email 'robot@menu.app'
          git add .
          git commit -m "Auto-Update Menu" || echo "Nessuna modifica"
          git push
